### ISSUE TITLE
Ollie croaks on null

### ISSUE THREAD

**Issue by schmmd** [knowitall/ollie#20]
If a token is "null", Ollie dies.

```
Figure III-2-16. Ideal case of an unstable null point (Walton 1972) . . . . . . . . . . . . . . . . . . . . . . III-2-36
Exception in thread "main" org.maltparser.core.symbol.SymbolException: Symbol table error: empty string cannot be added to the symbol table
    at org.maltparser.core.symbol.trie.TrieSymbolTable.addSymbol(TrieSymbolTable.java:81)
    at org.maltparser.core.syntaxgraph.GraphElement.addLabel(GraphElement.java:31)
    at org.maltparser.core.syntaxgraph.SyntaxGraph.addLabel(SyntaxGraph.java:35)
    at org.maltparser.MaltParserService.parse(MaltParserService.java:149)
    at edu.knowitall.tool.parse.MaltParser.dependencies(MaltParser.scala:96)
    at edu.knowitall.tool.parse.MaltParser.dependencyGraph(MaltParser.scala:122)
    at edu.knowitall.ollie.OllieCli$$anonfun$run$1$$anonfun$12$$anonfun$apply$mcV$sp$1$$anonfun$apply$7$$anonfun$25.apply(OllieCli.scala:249)
    at edu.knowitall.ollie.OllieCli$$anonfun$run$1$$anonfun$12$$anonfun$apply$mcV$sp$1$$anonfun$apply$7$$anonfun$25.apply(OllieCli.scala:249)
    at scala.Option.map(Option.scala:133)
    at edu.knowitall.ollie.OllieCli$$anonfun$run$1$$anonfun$12$$anonfun$apply$mcV$sp$1$$anonfun$apply$7.apply(OllieCli.scala:249)
    at edu.knowitall.ollie.OllieCli$$anonfun$run$1$$anonfun$12$$anonfun$apply$mcV$sp$1$$anonfun$apply$7.apply(OllieCli.scala:241)
    at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59)
    at scala.collection.immutable.List.foreach(List.scala:76)
    at edu.knowitall.ollie.OllieCli$$anonfun$run$1$$anonfun$12$$anonfun$apply$mcV$sp$1.apply(OllieCli.scala:241)
    at edu.knowitall.ollie.OllieCli$$anonfun$run$1$$anonfun$12$$anonfun$apply$mcV$sp$1.apply(OllieCli.scala:237)
    at scala.collection.Iterator$class.foreach(Iterator.scala:772)
    at scala.collection.Iterator$$anon$19.foreach(Iterator.scala:399)
    at edu.knowitall.ollie.OllieCli$$anonfun$run$1$$anonfun$12.apply$mcV$sp(OllieCli.scala:237)
    at edu.knowitall.common.Timing$.time(Timing.scala:59)
    at edu.knowitall.ollie.OllieCli$$anonfun$run$1.processSource$1(OllieCli.scala:226)
    at edu.knowitall.ollie.OllieCli$$anonfun$run$1$$anonfun$apply$12.apply(OllieCli.scala:290)
    at edu.knowitall.ollie.OllieCli$$anonfun$run$1$$anonfun$apply$12.apply(OllieCli.scala:289)
    at edu.knowitall.common.Resource$.using(Resource.scala:14)
    at edu.knowitall.ollie.OllieCli$$anonfun$run$1.apply(OllieCli.scala:289)
    at edu.knowitall.ollie.OllieCli$$anonfun$run$1.apply(OllieCli.scala:216)
    at edu.knowitall.common.Resource$.using(Resource.scala:14)
    at edu.knowitall.ollie.OllieCli$.run(OllieCli.scala:216)
    at edu.knowitall.ollie.OllieCli$.main(OllieCli.scala:174)
    at edu.knowitall.ollie.OllieCli.main(OllieCli.scala)
```

**Comment by zxybazh** [comment]
Same problem too. Simply trying "Life is null." can reproduce the bug.

**Comment by schmmd** [comment]
I'd happily accept a pull request, but there's no presently active development on Ollie.

**Comment by afader** [comment]
"Life is null" would make a great t-shirt.
