### ISSUE TITLE
My ollie can't work.

### ISSUE THREAD

**Issue by chenwangliangguo** [knowitall/ollie#23]
I have put the file "engmalt.linear-1.7.mco" in the correct position.

jar:file:/D:/JavaSpace/TweetsOIE/lib/ollie-app-latest.jar!/logback.xml
Initializing malt: -u file:/D:/JavaSpace/TweetsOIE/engmalt.linear-1.7.mco -m parse -cl off
Exception in thread "main" 
There was an error configurating MaltParser.
This is most likely because the model file 'file:/D:/JavaSpace/TweetsOIE/engmalt.linear-1.7.mco' was not found.
Please download the MaltParser model file from http://www.maltparser.org.

org.maltparser.core.config.ConfigurationException: The entry 'engmalt.linear-1.7_singlemalt.info' in the mco url 'file:/D:/JavaSpace/TweetsOIE/engmalt.linear-1.7.mco' cannot be loaded. 
    at org.maltparser.core.config.ConfigurationDir.getInputStreamReaderFromConfigFileEntry(ConfigurationDir.java:391)
    at org.maltparser.core.config.ConfigurationDir.initCreatedByMaltParserVersionFromInfoFile(ConfigurationDir.java:1031)
    at org.maltparser.core.config.ConfigDirChartItem.initialize(ConfigDirChartItem.java:93)
    at org.maltparser.core.flow.FlowChartInstance.initChartItem(FlowChartInstance.java:72)
    at org.maltparser.core.flow.FlowChartInstance.<init>(FlowChartInstance.java:53)
    at org.maltparser.core.flow.FlowChartManager.initialize(FlowChartManager.java:104)
    at org.maltparser.Engine.initialize(Engine.java:45)
    at org.maltparser.MaltParserService.initializeParserModel(MaltParserService.java:107)
    at edu.knowitall.tool.parse.MaltParser.initializeMaltParserService(MaltParser.scala:55)
    at edu.knowitall.tool.parse.MaltParser.<init>(MaltParser.scala:30)
    at ollie.JavaOllieWrapper.<init>(JavaOllieWrapper.java:26)
    at ollie.JavaOllieWrapper.main(JavaOllieWrapper.java:49)
Caused by: java.util.zip.ZipException: error in opening zip file
    at java.util.zip.ZipFile.open(Native Method)
    at java.util.zip.ZipFile.<init>(ZipFile.java:215)
    at java.util.zip.ZipFile.<init>(ZipFile.java:145)
    at java.util.jar.JarFile.<init>(JarFile.java:153)
    at java.util.jar.JarFile.<init>(JarFile.java:90)
    at sun.net.www.protocol.jar.URLJarFile.<init>(URLJarFile.java:93)
    at sun.net.www.protocol.jar.URLJarFile.getJarFile(URLJarFile.java:69)
    at sun.net.www.protocol.jar.JarFileFactory.get(JarFileFactory.java:94)
    at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:122)
    at sun.net.www.protocol.jar.JarURLConnection.getJarFile(JarURLConnection.java:89)
    at org.maltparser.core.config.ConfigurationDir.getInputStreamReaderFromConfigFileEntry(ConfigurationDir.java:378)
    ... 11 more

**Comment by schmmd** [comment]
I recommend using the Docker image that's listed in the README.
