### ISSUE TITLE
Java Version for Successful Build

### ISSUE THREAD

**Issue by rupsaijna** [knowitall/ollie#31]
Just a heads-up, as of March 2017, on Unix Systems, the Maven Build functionality for the project seems to work only with JDK 1.7
Also, even on successful build, executing it exits with the error:
Loading ollie models... Exception in thread "main" java.lang.reflect.InaccessibleObjectException: Unable to make member of class sun.net.www.protocol.jar.JarURLConnection$JarURLInputStream accessible:  module java.base does not export sun.net.www.protocol.jar to unnamed module @533377b
	at sun.reflect.Reflection.throwInaccessibleObjectException(java.base@9-internal/Reflection.java:420)
	at java.lang.reflect.AccessibleObject.checkCanSetAccessible(java.base@9-internal/AccessibleObject.java:174)
	at java.lang.reflect.Method.checkCanSetAccessible(java.base@9-internal/Method.java:189)
	at java.lang.reflect.Method.setAccessible(java.base@9-internal/Method.java:183)
	at scala.runtime.ScalaRunTime$.ensureAccessible(ScalaRunTime.scala:136)
	at edu.knowitall.common.Resource$.reflMethod$Method1(Resource.scala:16)
	at edu.knowitall.common.Resource$.using(Resource.scala:16)
	at edu.knowitall.openparse.OpenParse$.fromModelUrl(OpenParse.scala:175)
	at edu.knowitall.ollie.OllieCli$$anonfun$22.apply(OllieCli.scala:217)
	at edu.knowitall.ollie.OllieCli$$anonfun$22.apply(OllieCli.scala:212)
	at edu.knowitall.common.Timing$.time(Timing.scala:50)
	at edu.knowitall.common.Timing$.timeThen(Timing.scala:72)
	at edu.knowitall.ollie.OllieCli$.run(OllieCli.scala:219)
	at edu.knowitall.ollie.OllieCli$.main(OllieCli.scala:187)
	at edu.knowitall.ollie.OllieCli.main(OllieCli.scala)

**Comment by schmmd** [comment]
You can now run Ollie via Docker with `docker run -it schmmd/ollie:latest`.
